### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by sdmitrovic** [INFO-526-S24/project-01-Diwali-Dhamaka#1]
The following is the peer review of the project proposal by WackyWednesday. The team members that participated in this review are

    Jiayue He - @Melissajiayue
    Sanja Dmitrovic - @sdmitrovic
    Akash Srinivasan - @AkashSrinivasan12
    Navya Reddy - @navyareddy152
    Valerie Okine - @Valerie
    Gillian McGinnis - @gmcginnis

- Describe the goal of the project.

The goal of the project is to see how 1) gender and marital status of the customer affect which products they buy and 2) gender and age group of the customer affects how much they spend.

- Describe the data used or collected.

The data set is about sales and products during Diwali, which is a cultural festival. The variables include product category, gender, age group, marital status, etc.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The first question will be analyzed using a bar plot of how many customers buy products in various categories, where gender will be used to define the dodge position and a facet wrap will be created based on marital status. The second question will be explored using a bar plot, where the x-axis is age group. Gender will possibly be used to define dodge position or a facet wrap.

- Is there anything that is unclear from the proposal?

1. Are we sure that Marital_Status is 0 = married, 1 = single? 0/1 usually refers to False/True, so it seems like it would imply if    Marital_Status = 1 = True, that would be married.

2. It is unclear what country the data is coming from. We know Diwali is a holiday in India, but it is not explicitly stated in the proposal.

- Provide constructive feedback on how the team might be able to improve their project.

1. The descriptions of the variables are not included. This would be helpful for variables like "zone", where it's not immediately clear what it is.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

1. We look forward to seeing the relationship between marital status and sales, since this relationship is typically not examined.

- Provide constructive feedback on any issues with file and/or code organization.

1. Separate the list of variables by commas or indents.
3. Use an informative data frame name, rather than "df".
4. Questions should have a question mark at the end.
5. When referencing variable names, surround it with a backtick such that they will use the code formatting (e.g., "Product_Category" -> Product_Category).
6. Read.csv line should be one line instead of being separated into two lines.
7. Do not need to print libraries for the proposal page (in fact, no function used on that page is from the tidyverse so it is not needed for this particular page).

- (Optional) Any further comments or feedback?

1. Good use of str() to show a brief summary of the table!
2. Very specific analysis plan of action.

**Comment by Peter-Yeh-coder** [comment]
Marital_Status is in fact 1 = married, 0 = single. Changes have been made.
Addressed unclear data source in the analysis goal section.
Descriptions of variables have been added to a table.
Data frame names have been adjusted for the proposal. The presentation code will do the same.
Questions marks have been added to questions.
Referencing variable names are now surrounded with backticks.
Read.csv is now one line after putting .csv file in data folder.
Library R chunk now has echo set as false.
